import { BetsEntity } from "../pages/bets/components/ActiveBetsTable";
import { DrawItem } from "../pages/bets/components/DrawFilterBar";
import { ActiveDraw } from "../pages/dashboard/components/ActiveDrawTable";
import { ResultConfirmation } from "../pages/dashboard/components/ResultConfirmationTable";
import { ResultHistory } from "../pages/dashboard/components/ResultHistoryTable";
import { WinningHistory } from "../pages/dashboard/components/WinningHistoryTable";
import { LimitCombinationEntity } from "../pages/draw-settings/components/LimitCombinationTable";
import { SoldoutEntity } from "../pages/draw-settings/components/SoldoutCombinationTable";
import { WinningLimitSettingsData } from "../pages/draw-settings/components/WinningLimitSettings";
import { Game } from "../pages/draw-settings/DrawSettingsPage";
import { DrawScheduleEntity } from "../pages/game-configurations/components/DrawSchedulesTable";
import { LoadHistory } from "../pages/load-history/LoadHistoryPage";
import { Operator } from "../pages/operators/OperatorsPage";
import { Subscriber } from "../pages/subscribers/SubscribersPage";
import { TransferHistory } from "../pages/transfer-history/TransferHistoryPage";

export const mockActiveDrawData: ActiveDraw[] = [
    {
        key:1,
        gameType: '2D',
        drawDate: new Date('2023-10-01'),
        drawSchedule: '10:00 AM',
        cutoffStart: '09:00 AM',
        cutoffEnd: '09:30 AM',
        allowAdvanced: true,
        statusId: 1,
        statusName: 'Active',
        grossStraight: 1000,
        grossShuffle: 500,
        totalGross: 1500,
    },
    {
        key:2,
        gameType: '3D',
        drawDate: new Date('2023-10-02'),
        drawSchedule: '11:00 AM',
        cutoffStart: '10:00 AM',
        cutoffEnd: '10:30 AM',
        allowAdvanced: false,
        statusId: 2,
        statusName: 'Inactive',
        grossStraight: 2000,
        grossShuffle: 1000,
        totalGross: 3000,
    },
];

export const mockResultConfirmationData: ResultConfirmation[] = [
    {
        key: 1,
        gameType: '2D',
        drawDate: new Date('2023-10-01'),
        drawSchedule: '10:00 AM',
        cutoffStart: '09:00 AM',
        cutoffEnd: '09:30 AM',
        allowAdvanced: true,
        statusId: 1,
        statusName: 'Active',
        grossStraight: 1000,
        grossShuffle: 500,
        totalGross: 1500,
        winningsStraight: 800,
        winningsShuffle: 400,
        totalWinnings: 1200,
        postedBy: "James",
        datePosted: new Date('2023-10-01'),
    },
    {
        key: 2,
        gameType: '3D',
        drawDate: new Date('2023-10-02'),
        drawSchedule: '11:00 AM',
        cutoffStart: '10:00 AM',
        cutoffEnd: '10:30 AM',
        allowAdvanced: false,
        statusId: 2,
        statusName: 'Inactive',
        grossStraight: 2000,
        grossShuffle: 1000,
        totalGross: 3000,
        winningsStraight: 1600,
        winningsShuffle: 800,
        totalWinnings: 2400,
        postedBy: "Jessie",
        datePosted: new Date('2023-10-02'),
    }
];

export const mockResultHistoryData: ResultHistory[] = [
    {
        key: 1,
        gameType: '2D',
        drawDate: new Date('2025-04-06'),
        drawSchedule: '10:00 AM',
        cutoffStart: '09:00 AM',
        cutoffEnd: '09:30 AM',
        allowAdvanced: true,
        statusId: 1,
        statusName: 'Active',
        grossStraight: 1000,
        grossShuffle: 500,
        totalGross: 1500,
        winningsStraight: 800,
        winningsShuffle: 400,
        totalWinnings: 1200,
        postedBy: "James",
        datePosted: new Date('2025-04-06'),
        processedBy: "Admin",
        dateProcessed: new Date('2025-04-06'),
    },
    {
        key: 2,
        gameType: '3D',
        drawDate: new Date('2023-10-02'),
        drawSchedule: '11:00 AM',
        cutoffStart: '10:00 AM',
        cutoffEnd: '10:30 AM',
        allowAdvanced: false,
        statusId: 2,
        statusName: 'Inactive',
        grossStraight: 2000,
        grossShuffle: 1000,
        totalGross: 3000,
        winningsStraight: 1600,
        winningsShuffle: 800,
        totalWinnings: 2400,
        postedBy: "Jessie",
        datePosted: new Date('2023-10-02'),
        processedBy: "Admin",
        dateProcessed: new Date('2023-10-03'),
    }
];

export const mockWinningHistoryData: WinningHistory[] = [
    {
        key: 1,
        gameType: '2D',
        drawDate: new Date('2023-10-01'),
        drawSchedule: '10:00 AM',
        accountId: 12345,
        accountName: 'John Doe',
        transactionNumber: 'TXN123456',
        combination: '12-34',
        result: 'Win',
        betStraight: 100,
        betShuffle: 50,
        totalBet: 150,
        winStraight: 200,
        winShuffle: 100,
        datePosted: new Date('2023-10-01'),
        generalCoordinator: 'Alice',
        coordinator: 'Bob',
    },
    {
        key: 2,
        gameType: '3D',
        drawDate: new Date('2023-10-02'),
        drawSchedule: '11:00 AM',
        accountId: 67890,
        accountName: 'Jane Smith',
        transactionNumber: 'TXN654321',
        combination: '56-78-90',
        result: 'Loss',
        betStraight: 200,
        betShuffle: 100,
        totalBet: 300,
        winStraight: 0,
        winShuffle: 0,
        datePosted: new Date('2023-10-02'),
        generalCoordinator: 'Charlie',
        coordinator: 'Dave',
    }
]; 

export const mockActiveBetsData: BetsEntity[] = [
    {
        key: 1,
        gameType: '2D',
        drawDate: new Date('2023-10-01'),
        drawSchedule: '10:00 AM',
        accountId: 12345,
        accountName: 'John Doe',
        transactionNumber: 'TXN123456',
        combination: '12-34',
        betStraight: 100,
        betShuffle: 50,
        totalBet: 150,
        datePosted: new Date('2023-10-01'),
        generalCoordinator: 'Alice',
        coordinator: 'Bob',
    },
    {
        key: 2,
        gameType: '3D',
        drawDate: new Date('2023-10-02'),
        drawSchedule: '11:00 AM',
        accountId: 67890,
        accountName: 'Jane Smith',
        transactionNumber: 'TXN654321',
        combination: '56-78-90',
        betStraight: 200,
        betShuffle: 100,
        totalBet: 300,
        datePosted: new Date('2023-10-02'),
        generalCoordinator: 'Charlie',
        coordinator: 'Dave',
    }
];

export const drawOptions: DrawItem[] = [
  { gameType: '2D', drawDate: '2025-03-24T17:00:00' },
  { gameType: '3D', drawDate: '2025-03-24T17:00:00' },
];

export const mockGames: Game[] = [
    {
        key: 1,
        gameName: '2D',
        gameId: 1,
    },
    {
        key: 2,
        gameName: '3D',
        gameId: 2,
    },
    {
        key: 3,
        gameName: 'LAST2',
        gameId: 3,
    }
];

export const mockWinningSettingsData: WinningLimitSettingsData = {
    id: 1,
    winningAmount:600,
    straightLimit:200,
    rumbleLimit:200,

}

export const mockLimitCombinations: LimitCombinationEntity[] = [
    {
        key: 1,
        combination: 'A-J-4',
        straightLimit: 200,
        rumbleLimit: 100,
    },
    {
        key: 2,
        combination: '10-10-10',
        straightLimit: 400,
        rumbleLimit: 200,
    }
];

export const mockLoadHistory: LoadHistory[] = [
  {
    accountName: "john_doe123",
    amount: 500,
    transactionDate: new Date("2025-04-01T10:30:00"),
    transactedBy: "admin1",
  },
  {
    accountName: "jane_smith",
    amount: 1000,
    transactionDate: new Date("2025-04-03T14:45:00"),
    transactedBy: "cashier02",
  },
  {
    accountName: "lucky_player7",
    amount: 750,
    transactionDate: new Date("2025-04-05T09:15:00"),
    transactedBy: "superadmin",
  },
  {
    accountName: "bet_master88",
    amount: 1200,
    transactionDate: new Date("2025-04-08T17:20:00"),
    transactedBy: "admin2",
  },
  {
    accountName: "slotqueen",
    amount: 300,
    transactionDate: new Date("2025-04-09T11:05:00"),
    transactedBy: "cashier01",
  },
];

export const mockTransferHistory: TransferHistory[] = [
  {
    sourceAccount: "john_doe123",
    destinationAccount: "Sample a",
    amount: 500,
    transactionDate: new Date("2025-04-01T10:30:00"),
    transactedBy: "admin1",
  },
  {
    sourceAccount: "jane_smith",
    destinationAccount: "Sample B",
    amount: 1000,
    transactionDate: new Date("2025-04-03T14:45:00"),
    transactedBy: "cashier02",
  },
  {
    sourceAccount: "lucky_player7",
    destinationAccount: "Juan",
    amount: 750,
    transactionDate: new Date("2025-04-05T09:15:00"),
    transactedBy: "superadmin",
  },
  {
    sourceAccount: "bet_master88",
    destinationAccount: "Two",
    amount: 1200,
    transactionDate: new Date("2025-04-08T17:20:00"),
    transactedBy: "admin2",
  },
  {
    sourceAccount: "slotqueen",
    destinationAccount: "Three",
    amount: 300,
    transactionDate: new Date("2025-04-09T11:05:00"),
    transactedBy: "cashier01",
  },
];

export const mockSubscribersList: Subscriber[] = [
  
  {
    accountName: "jane_doe",
    mobileNumber: "09171234567",
    upline: "admin001",
    accountType: "Retailer",
    creditBalance: 1500,
    gender: 1,
    birthDate: new Date("1990-06-12"),
    region: "Region IV-A",
    province: "Laguna",
    municipality: "San Pablo",
    barangay: "Barangay 1",
    completeAddress: "Barangay 1, San Pablo City, Laguna",
    dateRegistered: new Date("2024-08-10"),
    isBlocked: false,
  },
  {
    accountName: "mike_casino",
    mobileNumber: "09281234567",
    upline: "agentX",
    accountType: "Agent",
    creditBalance: 2500,
    gender: 0,
    birthDate: new Date("1985-02-18"),
    region: "NCR",
    province: "Metro Manila",
    municipality: "Quezon City",
    barangay: "Commonwealth",
    completeAddress: "Blk 12 Commonwealth Ave, Quezon City",
    dateRegistered: new Date("2024-09-21"),
    isBlocked: false,
  },
  {
    accountName: "sunshine88",
    mobileNumber: "09081239876",
    upline: "admin001",
    accountType: "Retailer",
    creditBalance: 800,
    gender: 1,
    birthDate: new Date("1993-03-03"),
    region: "Region VII",
    province: "Cebu",
    municipality: "Cebu City",
    barangay: "Mabolo",
    completeAddress: "Mabolo, Cebu City",
    dateRegistered: new Date("2025-01-03"),
    isBlocked: false,
  },
  {
    accountName: "jackpot_king",
    mobileNumber: "09184561234",
    upline: "superadmin",
    accountType: "Sub-agent",
    creditBalance: 3200,
    gender: 0,
    birthDate: new Date("1988-11-23"),
    region: "Region I",
    province: "Ilocos Norte",
    municipality: "Laoag",
    barangay: "Barangay 7",
    completeAddress: "Brgy 7, Laoag City",
    dateRegistered: new Date("2024-12-15"),
    isBlocked: false,
  },
  {
    accountName: "prettybet123",
    mobileNumber: "09175678901",
    upline: "agentY",
    accountType: "Retailer",
    creditBalance: 500,
    gender: 1,
    birthDate: new Date("1995-09-09"),
    region: "Region III",
    province: "Pampanga",
    municipality: "Angeles",
    barangay: "Balibago",
    completeAddress: "Balibago, Angeles City",
    dateRegistered: new Date("2025-03-10"),
    isBlocked: false,
  },
  {
    accountName: "winner_777",
    mobileNumber: "09324561234",
    upline: "admin002",
    accountType: "Retailer",
    creditBalance: 1200,
    gender: 0,
    birthDate: new Date("1992-07-14"),
    region: "Region VI",
    province: "Iloilo",
    municipality: "Iloilo City",
    barangay: "Jaro",
    completeAddress: "Jaro, Iloilo City",
    dateRegistered: new Date("2024-10-01"),
    isBlocked: true,
  },
  {
    accountName: "luckystrike",
    mobileNumber: "09273219876",
    upline: "agentX",
    accountType: "Sub-agent",
    creditBalance: 1750,
    gender: 1,
    birthDate: new Date("1991-05-22"),
    region: "Region V",
    province: "Albay",
    municipality: "Legazpi",
    barangay: "Rawis",
    completeAddress: "Rawis, Legazpi City",
    dateRegistered: new Date("2024-11-17"),
    isBlocked: false,
  },
  {
    accountName: "super_user001",
    mobileNumber: "09174561239",
    upline: "superadmin",
    accountType: "Agent",
    creditBalance: 5400,
    gender: 0,
    birthDate: new Date("1982-01-01"),
    region: "CAR",
    province: "Benguet",
    municipality: "Baguio",
    barangay: "Pacdal",
    completeAddress: "Pacdal, Baguio City",
    dateRegistered: new Date("2025-02-01"),
    isBlocked: false,
  },
  {
    accountName: "betqueen",
    mobileNumber: "09181122334",
    upline: "agentZ",
    accountType: "Retailer",
    creditBalance: 920,
    gender: 1,
    birthDate: new Date("1996-04-25"),
    region: "Region VIII",
    province: "Leyte",
    municipality: "Tacloban",
    barangay: "Downtown",
    completeAddress: "Downtown, Tacloban City",
    dateRegistered: new Date("2025-01-20"),
    isBlocked: false,
  },
  {
    accountName: "playerzero",
    mobileNumber: "09072349876",
    upline: "admin001",
    accountType: "Retailer",
    creditBalance: 0,
    gender: 0,
    birthDate: new Date("1999-10-10"),
    region: "Region XII",
    province: "South Cotabato",
    municipality: "Koronadal",
    barangay: "Zone III",
    completeAddress: "Zone III, Koronadal",
    dateRegistered: new Date("2025-03-25"),
    isBlocked: true,
  },
  {
    accountName: "finalbet",
    mobileNumber: "09181239876",
    upline: "agentY",
    accountType: "Sub-agent",
    creditBalance: 1350,
    gender: 0,
    birthDate: new Date("1987-08-08"),
    region: "Region IX",
    province: "Zamboanga del Sur",
    municipality: "Zamboanga City",
    barangay: "Tumaga",
    completeAddress: "Tumaga, Zamboanga City",
    dateRegistered: new Date("2025-04-02"),
    isBlocked: false,
  },
];

export const mockOperatorsList: Operator[] = [
  
  {
    accountName: "jane_doe",
    mobileNumber: "09171234567",
    upline: "admin001",
    accountType: "Retailer",
    creditBalance: 1500,
    gender: 1,
    birthDate: new Date("1990-06-12"),
    region: "Region IV-A",
    province: "Laguna",
    municipality: "San Pablo",
    barangay: "Barangay 1",
    completeAddress: "Barangay 1, San Pablo City, Laguna",
    dateRegistered: new Date("2024-08-10"),
    isBlocked: false,
  },
  {
    accountName: "mike_casino",
    mobileNumber: "09281234567",
    upline: "agentX",
    accountType: "Agent",
    creditBalance: 2500,
    gender: 0,
    birthDate: new Date("1985-02-18"),
    region: "NCR",
    province: "Metro Manila",
    municipality: "Quezon City",
    barangay: "Commonwealth",
    completeAddress: "Blk 12 Commonwealth Ave, Quezon City",
    dateRegistered: new Date("2024-09-21"),
    isBlocked: false,
  },
  {
    accountName: "sunshine88",
    mobileNumber: "09081239876",
    upline: "admin001",
    accountType: "Retailer",
    creditBalance: 800,
    gender: 1,
    birthDate: new Date("1993-03-03"),
    region: "Region VII",
    province: "Cebu",
    municipality: "Cebu City",
    barangay: "Mabolo",
    completeAddress: "Mabolo, Cebu City",
    dateRegistered: new Date("2025-01-03"),
    isBlocked: false,
  },
  {
    accountName: "jackpot_king",
    mobileNumber: "09184561234",
    upline: "superadmin",
    accountType: "Sub-agent",
    creditBalance: 3200,
    gender: 0,
    birthDate: new Date("1988-11-23"),
    region: "Region I",
    province: "Ilocos Norte",
    municipality: "Laoag",
    barangay: "Barangay 7",
    completeAddress: "Brgy 7, Laoag City",
    dateRegistered: new Date("2024-12-15"),
    isBlocked: false,
  },
  {
    accountName: "prettybet123",
    mobileNumber: "09175678901",
    upline: "agentY",
    accountType: "Retailer",
    creditBalance: 500,
    gender: 1,
    birthDate: new Date("1995-09-09"),
    region: "Region III",
    province: "Pampanga",
    municipality: "Angeles",
    barangay: "Balibago",
    completeAddress: "Balibago, Angeles City",
    dateRegistered: new Date("2025-03-10"),
    isBlocked: false,
  },
  {
    accountName: "winner_777",
    mobileNumber: "09324561234",
    upline: "admin002",
    accountType: "Retailer",
    creditBalance: 1200,
    gender: 0,
    birthDate: new Date("1992-07-14"),
    region: "Region VI",
    province: "Iloilo",
    municipality: "Iloilo City",
    barangay: "Jaro",
    completeAddress: "Jaro, Iloilo City",
    dateRegistered: new Date("2024-10-01"),
    isBlocked: true,
  },
  {
    accountName: "luckystrike",
    mobileNumber: "09273219876",
    upline: "agentX",
    accountType: "Sub-agent",
    creditBalance: 1750,
    gender: 1,
    birthDate: new Date("1991-05-22"),
    region: "Region V",
    province: "Albay",
    municipality: "Legazpi",
    barangay: "Rawis",
    completeAddress: "Rawis, Legazpi City",
    dateRegistered: new Date("2024-11-17"),
    isBlocked: false,
  },
  {
    accountName: "super_user001",
    mobileNumber: "09174561239",
    upline: "superadmin",
    accountType: "Agent",
    creditBalance: 5400,
    gender: 0,
    birthDate: new Date("1982-01-01"),
    region: "CAR",
    province: "Benguet",
    municipality: "Baguio",
    barangay: "Pacdal",
    completeAddress: "Pacdal, Baguio City",
    dateRegistered: new Date("2025-02-01"),
    isBlocked: false,
  },
  {
    accountName: "betqueen",
    mobileNumber: "09181122334",
    upline: "agentZ",
    accountType: "Retailer",
    creditBalance: 920,
    gender: 1,
    birthDate: new Date("1996-04-25"),
    region: "Region VIII",
    province: "Leyte",
    municipality: "Tacloban",
    barangay: "Downtown",
    completeAddress: "Downtown, Tacloban City",
    dateRegistered: new Date("2025-01-20"),
    isBlocked: false,
  },
  {
    accountName: "playerzero",
    mobileNumber: "09072349876",
    upline: "admin001",
    accountType: "Retailer",
    creditBalance: 0,
    gender: 0,
    birthDate: new Date("1999-10-10"),
    region: "Region XII",
    province: "South Cotabato",
    municipality: "Koronadal",
    barangay: "Zone III",
    completeAddress: "Zone III, Koronadal",
    dateRegistered: new Date("2025-03-25"),
    isBlocked: true,
  },
  {
    accountName: "finalbet",
    mobileNumber: "09181239876",
    upline: "agentY",
    accountType: "Sub-agent",
    creditBalance: 1350,
    gender: 0,
    birthDate: new Date("1987-08-08"),
    region: "Region IX",
    province: "Zamboanga del Sur",
    municipality: "Zamboanga City",
    barangay: "Tumaga",
    completeAddress: "Tumaga, Zamboanga City",
    dateRegistered: new Date("2025-04-02"),
    isBlocked: false,
  },
];


export const mockFetchLimitCombinations = (): Promise<LimitCombinationEntity[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([
            {
              key: 1,
              combination: "1-5-5",
              straightLimit: 100000,
              rumbleLimit: 100000,
            },
            {
              key: 2,
              combination: "2-2-8",
              straightLimit: 50000,
              rumbleLimit: 80000,
            },
            {
              key: 3,
              combination: "0-1-5",
              straightLimit: 120000,
              rumbleLimit: 150000,
            },
            {
              key: 4,
              combination: "3-7-3",
              straightLimit: 40000,
              rumbleLimit: 60000,
            },
            {
              key: 5,
              combination: "6-4-9",
              straightLimit: 200000,
              rumbleLimit: 180000,
            },
            {
              key: 6,
              combination: "4-8-6",
              straightLimit: 75000,
              rumbleLimit: 90000,
            },
        ]);
      }, 500);
    });
  };

  export const mockSoldoutCombinations = (): Promise<SoldoutEntity[]> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([
          {
            key: 2,
            combination: "2-2-8",
          },
          {
            key: 5,
            combination: "6-4-9",
          },
          {
            key: 6,
            combination: "4-8-6",
          },
        ]);
      }, 500);
    });
  };
  
export const fetchMockDrawSchedules = (): Promise<DrawScheduleEntity[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          key: '1',
          scheduleName: 'Morning Draw',
          cutoffStart: '2025-04-11T08:00:00.000Z',
          cutoffEnd: '2025-04-11T08:30:00.000Z',
        },
        {
          key: '2',
          scheduleName: 'Midday Draw',
          cutoffStart: '2025-04-11T12:00:00.000Z',
          cutoffEnd: '2025-04-11T12:30:00.000Z',
        },
        {
          key: '3',
          scheduleName: 'Evening Draw',
          cutoffStart: '2025-04-11T18:00:00.000Z',
          cutoffEnd: '2025-04-11T18:30:00.000Z',
        },
        {
          key: '4',
          scheduleName: 'Late Night Draw',
          cutoffStart: '2025-04-11T22:00:00.000Z',
          cutoffEnd: '2025-04-11T22:30:00.000Z',
        },
      ]);
    }, 500); // Simulate 500ms network delay
  });
};